version: '3.8'

services:
  db:
    image: postgis/postgis:15-3.3
    container_name: ithome_project
    restart: always
    environment:
      POSTGRES_USER: vessel
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: gis_data
    ports:
      - "5432:5432"
    volumes:
      - gis_db_data:/var/lib/postgresql/data

volumes:
  gis_db_data: